// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewECO5.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewECO5.Migrations
{
    [DbContext(typeof(NewECO5DBContext))]
    [Migration("20250730013741_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewECO5.Models.Enum.MeterSetting", b =>
                {
                    b.Property<int>("SerialNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SerialNr"));

                    b.Property<bool>("IsActived")
                        .HasColumnType("boolean");

                    b.Property<byte>("MeterID")
                        .HasColumnType("smallint");

                    b.Property<short>("MetersGroupSetting_Id")
                        .HasColumnType("smallint");

                    b.Property<int?>("ModbusMode")
                        .HasColumnType("integer");

                    b.Property<string>("ProtocolStr")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<short>("Protocol_Id")
                        .HasColumnType("smallint");

                    b.HasKey("SerialNr");

                    b.HasIndex("SerialNr")
                        .IsUnique();

                    b.ToTable("MeterSettings", (string)null);
                });

            modelBuilder.Entity("NewECO5.Models.MetersGroupSetting", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("ConnectionStr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IsTCPSetting")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MetersGroupSettings");
                });

            modelBuilder.Entity("NewECO5.Models.PowerMeterSetting", b =>
                {
                    b.Property<int>("SerialNr")
                        .HasColumnType("integer");

                    b.Property<float>("Alarm_HzLowerLimit")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_HzUpperLimit")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_I_LowerLimit")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_I_UpperLimit")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_KWh_UpperLimit")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_PfLowerLimit")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_PfUpperLimit")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_V_LowerLimit")
                        .HasColumnType("real");

                    b.Property<int>("Alarm_V_Type")
                        .HasColumnType("integer");

                    b.Property<float>("Alarm_V_UpperLimit")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_kW_IdelValue")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_kW_LowerLimit")
                        .HasColumnType("real");

                    b.Property<float>("Alarm_kW_UpperLimit")
                        .HasColumnType("real");

                    b.Property<DateTime>("Alarm_notPowerOffAlarmEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Alarm_notPowerOffAlarmStartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("Alarm_notPowerOff_kW")
                        .HasColumnType("real");

                    b.Property<float?>("Area")
                        .HasColumnType("real");

                    b.Property<bool>("AutoReset")
                        .HasColumnType("boolean");

                    b.Property<int>("BufferToKeep")
                        .HasColumnType("integer");

                    b.Property<string>("CustomName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float?>("CustomValue")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DiagramNr")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<float>("Dmd_Capacity")
                        .HasColumnType("real");

                    b.Property<float>("Dmd_CapacityHalf")
                        .HasColumnType("real");

                    b.Property<float>("Dmd_CapacityOff")
                        .HasColumnType("real");

                    b.Property<float>("Dmd_CapacitySatHalf")
                        .HasColumnType("real");

                    b.Property<float>("Dmd_Interval")
                        .HasColumnType("real");

                    b.Property<float>("Dmd_LowerLimit")
                        .HasColumnType("real");

                    b.Property<int>("Dmd_Mode")
                        .HasColumnType("integer");

                    b.Property<float>("Dmd_UpperLimit")
                        .HasColumnType("real");

                    b.Property<bool>("IsLowVoltage")
                        .HasColumnType("boolean");

                    b.Property<float>("KVA_Diff")
                        .HasColumnType("real");

                    b.Property<float>("KW_Check_limit")
                        .HasColumnType("real");

                    b.Property<int?>("Persons")
                        .HasColumnType("integer");

                    b.HasKey("SerialNr");

                    b.ToTable("PowerMeterSettings", (string)null);
                });

            modelBuilder.Entity("NewECO5.Models.Protocol", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("Loop")
                        .HasColumnType("smallint");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WiringMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Protocols");
                });

            modelBuilder.Entity("NewECO5.Models.PowerMeterSetting", b =>
                {
                    b.HasOne("NewECO5.Models.Enum.MeterSetting", "MeterSetting")
                        .WithOne()
                        .HasForeignKey("NewECO5.Models.PowerMeterSetting", "SerialNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeterSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
